model = "Ising"

[sample.unitcell]
name = "sc"

[sample.size]
x = 10
y = 10
z = 1

[sample.pbc]
x = true
y = true
z = false

[[steps]]
program = "Relax"
steps = 1000
temperature = 4.0

[[steps]]
program = "CoolDown"
max_temperature = 4.0
min_temperature = 0.1
cool_rate = 0.1
relax = 1000
steps = 20000

[output]
raw = "./output.parquet"

[output.state]
path = "./state.parquet"
frequency = 1000
